site_name: Parkinsonâ€™s Annotator Documents

theme:
  name: material

plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Installation Manual: INSTALLATION.md
  - User Manual: USER_MANUAL.md
  - Technical Manual: TECHNICAL_MANUAL.md
  - Docker: DOCKER.md